space/core/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index')
]

space/space/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('team/', include('team.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

space/team/urls.py
from django.urls import path
from . import views


app_name = 'spaceteam'

urlpatterns = [
    path('', views.spaceteam, name='team')
]

space/core/models.py
from django.db import models

# Create your models here.


class WhoAreWe(models.Model):
    text = models.TextField()
    image = models.ImageField(upload_to='main_images')


class Achivements(models.Model):
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=255)
    image = models.ImageField(upload_to='achivements')

space/team/models.py
from django.db import models

# Create your models here.

class Member(models.Model):
    name = models.CharField(max_length=255, null=False)
    role = models.CharField(max_length=255, null=False)
    description = models.TextField()
    image = models.ImageField(upload_to='members')

    def __str__(self):
        return self.name

space/core/views.py
from django.shortcuts import render, get_object_or_404
from .models import WhoAreWe, Achivements
# Create your views here.


def index(request):
    whoarewe = WhoAreWe.objects.all()
    achive = Achivements.objects.all()
    return render(request, 'core/index.html', {
        'whoarewe': whoarewe,
        'achive': achive
    })

space/team/views.py
from django.shortcuts import render
from .models import Member

# Create your views here.

def spaceteam(request):
    members = Member.objects.all()
    return render(request, 'team/team.html', {
        'members': members
    })

space/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} | SPACE VISION</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="icon" href="{% static 'assets/images/menulogo.png' %}">
    <!-- <link rel="stylesheet" href="./assets/css/style.css"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>

<body>
    <header class="home">
        <nav class="navbar navbar-expand-lg bg-50">
            <div class="container">
                <a class="navbar-brand logo" href="./index.html"><img src="{% static 'assets/images/menulogo.png' %}" alt="">
                    <h2>SPACE VISION</h2>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                       
                            <a class="nav-link" href="{% url 'spaceteam:team' %}">Our team</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="outreach.html">Outreach</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="tutorials.html">tutorials</a>

                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <section class="py-5">
            <div class="mt-5">
                <img src="{% static 'assets/images/hero.png' %}" alt="">
            </div>
            <div class="pb-5">
                <a href="./tutorials.html"><button class="btn-brand">
                        Tutorials
                    </button></a>
            </div>
        </section>
    </header>


    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer>
        <div class="container">
            <div class="footer_area row align-items-center py-5">
                <div class="col-md-2 mt-3"><img src=" {% static 'assets/images/footerlogo.png' %}" alt=""></div>
                <div class="col-md-4 mt-3">
                    <div>
                        <p><b>PHONE</b></p>
                        <p>+77772133301</p>
                        <p>+77078184242</p>
                    </div>
                </div>
                <div class="col-md-3 mt-3">
                    <div>
                        <p><b>CONTACT</b></p>
                        <p>email: aspacevision@gmail.com</p>
                        <p>adress: Bayzakov str., 280, SmArt.Point | 1 floor</p>
                    </div>
                </div>
                <div class="col-md-3 mt-3">
                    <div>
                        <p><b>SOCIALS</b></p>
                        <p><a href="https://www.instagram.com/aspacevision/">Instagram</a></p>
                        <p><a href="https://www.facebook.com/aspacevision">Facebook</a></p>
                        <p><a href="">LinkedIn</a></p>
                    </div>
                </div>


            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>

</html>

space/core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

{% block title %}
    Home
{% endblock %}

{% block content %}
    {% for who in whoarewe %}
    <section class="who-we-are mb-5 flex">
        <div class="container">
            <div class="who-we-are-content row">
                <div class="col-md-6">
                    <div class="who-we-are-content-left my-5">
                        <h1>WHO ARE WE?</h1>
                        <img src="{{ who.image.url }}" alt="">
                        <!-- <img src="{% static 'assets/images/homewhoweare.png' %}" alt=""> -->
                        <!-- ./assets/images/homewhoweare.png -->
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="who-we-are-content-right">
                        {{ who.text }}
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endfor %}
    <!-- OUR ACHIEVEMENTS -->


    <section class="our-achievements mt-5">
        <div class="container">
            <h1>OUR ACHIEVEMENTS</h1>
            <div class="our-achievements-content row">
                {% for ach in achive %}
                <div class="col-md-4">
                    <div class="our-achievements-content-single">
                        <img src="{{ ach.image.url }}" alt="">
                        <div class="our-achievements-content-single-footer">
                            <h4>{{ ach.title }}</h4>
                            <p>
                                {{ ach.text }}
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}


            </div>
        </div>
    </section>

    
{% endblock %}

space/team/templates/team/team.html
{% load static %}
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<link rel="icon" href="{% static 'assets/images/menulogo.png' %}">
<!-- <link rel="stylesheet" href="./assets/css/style.css"> -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

<header class="teamspage">
    <nav class="navbar navbar-expand-lg  ">
        <div class="container">
            <a class="navbar-brand logo" href="{% url 'main:index' %}"><img src="{% static 'assets/images/menulogo.png' %}" alt="">
                <h2>SPACE VISION</h2>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'main:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'spaceteam:team' %}">Our team</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="outreach.html">Outreach</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="tutorials.html">tutorials</a>

                    </li>
                </ul>
            </div>
        </div>
    </nav>


</header>


<section class="ourteams">
    <div class="container">
        <h1>OUR TEAM</h1>
        <div class="our_teams">
            {% for member in members %}
            <div class="our_teams_single">
                <div>
                    <img src="{{ member.image.url }}" alt="">
                    <div class="btn_position">
                        {{ member.role }}
                    </div>
                </div>

                <div class="our_teams_single_footer">
                    <h3>{{ member.name }}</h3>
                    <p>{{ member.description }}</p>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</section>